name = {
  id: 43938,
  type: "query",
  flags: 288,
  flag_qr: false,
  opcode: "QUERY",
  flag_aa: false,
  flag_tc: false,
  flag_rd: true,
  flag_ra: false,
  flag_z: false,
  flag_ad: true,
  flag_cd: false,
  rcode: "NOERROR",
  questions: [{ name: "amazon.com", type: "A", class: "IN" }],
  answers: [],
  authorities: [],
  additionals: [
    {
      name: ".",
      type: "OPT",
      udpPayloadSize: 4096,
      extendedRcode: 0,
      ednsVersion: 0,
      flags: 0,
      flag_do: false,
      options: [Array],
    },
  ],
};
